# Generated by Django 5.0.7 on 2024-08-18 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0004_remove_doi_cau_thu_cauthu_doi"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranDau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngay_thi_dau", models.DateField()),
                ("gio_thi_dau", models.TimeField()),
                ("dia_diem", models.CharField(max_length=100)),
                (
                    "doi_khach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doi_khach",
                        to="Home.doi",
                    ),
                ),
                (
                    "doi_nha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doi_nha",
                        to="Home.doi",
                    ),
                ),
            ],
        ),
    ]
