# Generated by Django 5.0.7 on 2024-08-02 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_doi_delete_test_alter_cauthu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doi',
            name='cau_thu',
        ),
        migrations.AddField(
            model_name='cauthu',
            name='doi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.doi'),
        ),
    ]
