# Generated by Django 5.0.7 on 2024-08-18 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0005_trandau"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trandau",
            name="dia_diem",
        ),
        migrations.AddField(
            model_name="trandau",
            name="san_dau",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="san_dau",
                to="Home.doi",
            ),
            preserve_default=False,
        ),
    ]
