# Generated by Django 5.0.7 on 2024-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0006_remove_trandau_dia_diem_trandau_san_dau"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trandau",
            name="san_dau",
            field=models.CharField(max_length=100),
        ),
    ]
