# Generated by Django 5.1 on 2024-08-19 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0008_ghinhanketqua"),
    ]

    operations = [
        migrations.CreateModel(
            name="KetQua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ty_so", models.CharField(default="0-0", max_length=5)),
                ("san", models.CharField(max_length=255)),
                ("ngay", models.DateField()),
                ("gio", models.TimeField()),
                (
                    "loai_ban_thang",
                    models.CharField(
                        choices=[
                            ("THUONG", "Bàn thắng thường"),
                            ("PHAT_DEN", "Penalty"),
                            ("TU_CUOI", "Phản lưới nhà"),
                        ],
                        default="THUONG",
                        max_length=10,
                    ),
                ),
                (
                    "thoi_diem",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(96),
                        ]
                    ),
                ),
                (
                    "cau_thu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.cauthu"
                    ),
                ),
                (
                    "doi_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ghi_nhan_doi_1",
                        to="Home.doi",
                    ),
                ),
                (
                    "doi_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ghi_nhan_doi_2",
                        to="Home.doi",
                    ),
                ),
                (
                    "doi_ghi_ban",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doi_ghi_ban",
                        to="Home.doi",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ghi Nhận Kết Quả",
            },
        ),
        migrations.DeleteModel(
            name="GhiNhanKetQua",
        ),
    ]
