# Generated by Django 5.1 on 2024-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_muagiai_trandau_mua_giai'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauthu',
            name='so_ban_thang',
            field=models.IntegerField(default=0),
        ),
    ]
